/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author J
 */
public class tugas2 extends javax.swing.JFrame {

    /**
     * Creates new form tugas2
     */
    public tugas2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Absen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Mapel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Nilai = new javax.swing.JTextField();
        ButtonProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        ButtonReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        HB1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        HB2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        HB3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        DISKON = new javax.swing.JTextField();
        ButtonProses1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Bellerose", 1, 24)); // NOI18N
        jLabel1.setText("Penilaian");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Absen");

        Absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbsenActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mapel");

        Mapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bellerose", 1, 24)); // NOI18N
        jLabel5.setText("Hasil :");

        Nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaiActionPerformed(evt);
            }
        });

        ButtonProses.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonProses.setText("Proses");
        ButtonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProsesActionPerformed(evt);
            }
        });

        TA.setEditable(false);
        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nilai");

        ButtonReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonReset.setForeground(new java.awt.Color(255, 0, 0));
        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Bellerose", 1, 24)); // NOI18N
        jLabel7.setText("Pembayaran");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 0, 150, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Harga Barang 1");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 50, 110, 30);

        HB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HB1ActionPerformed(evt);
            }
        });
        getContentPane().add(HB1);
        HB1.setBounds(160, 50, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Harga Barang 2");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 90, 110, 30);

        HB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HB2ActionPerformed(evt);
            }
        });
        getContentPane().add(HB2);
        HB2.setBounds(160, 90, 160, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Harga Barang 3");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 130, 110, 30);

        HB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HB3ActionPerformed(evt);
            }
        });
        getContentPane().add(HB3);
        HB3.setBounds(160, 130, 160, 30);

        jLabel11.setFont(new java.awt.Font("Bellerose", 1, 24)); // NOI18N
        jLabel11.setText("Total Bayar :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 200, 140, 50);

        DISKON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISKONActionPerformed(evt);
            }
        });
        getContentPane().add(DISKON);
        DISKON.setBounds(160, 170, 160, 30);

        ButtonProses1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonProses1.setText("Proses");
        ButtonProses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProses1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonProses1);
        ButtonProses1.setBounds(30, 290, 73, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Dskon");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 170, 110, 30);

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane3.setViewportView(Hasil);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(150, 270, 210, 150);

        setBounds(0, 0, 416, 481);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void AbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbsenActionPerformed

    private void MapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MapelActionPerformed

    private void NilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NilaiActionPerformed

    private void ButtonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProsesActionPerformed
        // TODO add your handling code here:
        String nama = Nama.getText();
        int absen = Integer.parseInt(Absen.getText());
        String mapel = Mapel.getText();
        int nilai = Integer.parseInt(Nilai.getText());

        if(nilai <= 74)
        {
            TA.setText("Nama :"+ nama+"\n"+"Absen :"+ absen+"\n"+"Mapel :"+ mapel+"\n"+"Nilai :"+ nilai+"\n"+"Predikat : Tidak Lulus");
        }
        else if(nilai >= 75 && nilai <= 85)
        {Nama.setText("");
            Absen.setText("");
            TA.setText("Nama :"+ nama+"\n"+"Absen :"+ absen+"\n"+"Mapel :"+ mapel+"\n"+"Nilai :"+ nilai+"\n"+"Predikat : Lulus");
        }
        else
        {
            TA.setText("Nama :"+ nama+"\n"+"Absen :"+ absen+"\n"+"Mapel :"+ mapel+"\n"+"Nilai :"+ nilai+"\n"+"Predikat : Sempurna");
        }
    }//GEN-LAST:event_ButtonProsesActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Absen.setText("");
        Mapel.setText("");
        Nilai.setText("");
        TA.setText("");
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void HB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HB1ActionPerformed

    private void HB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HB2ActionPerformed

    private void HB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HB3ActionPerformed

    private void DISKONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISKONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DISKONActionPerformed

    private void ButtonProses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProses1ActionPerformed
        // TODO add your handling code here:
        int hbrg1 = Integer.parseInt(HB1.getText());
        int hbrg2 = Integer.parseInt(HB2.getText());
        int hbrg3 = Integer.parseInt(HB3.getText());
        int diskon = Integer.parseInt(DISKON.getText());
        int tothrg = hbrg1+hbrg2+hbrg3;
        int dis = tothrg*diskon/100;
        int hasil = tothrg-dis;
        Hasil.setText("Harga Barang 1 : "+ hbrg1 +"\n"+
                "Harga Barang 2 : "+ hbrg2+"\n"+
                "Harga Barang 3 : "+ hbrg3+"\n"+
                "Total Harga : "+ (String.valueOf(tothrg)) +"\n"+
                "Diskon : "+diskon+"%\n"+
                "Jumlah Bayar : "+(String.valueOf(hasil)));
    }//GEN-LAST:event_ButtonProses1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JButton ButtonProses;
    private javax.swing.JButton ButtonProses1;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JTextField DISKON;
    private javax.swing.JTextField HB1;
    private javax.swing.JTextField HB2;
    private javax.swing.JTextField HB3;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JTextField Mapel;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nilai;
    private javax.swing.JTextArea TA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
